// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"flashvid-platform/internal/model"
)

func newMusic(db *gorm.DB, opts ...gen.DOOption) music {
	_music := music{}

	_music.musicDo.UseDB(db, opts...)
	_music.musicDo.UseModel(&model.Music{})

	tableName := _music.musicDo.TableName()
	_music.ALL = field.NewAsterisk(tableName)
	_music.ID = field.NewInt64(tableName, "id")
	_music.Name = field.NewString(tableName, "name")
	_music.Artist = field.NewString(tableName, "artist")
	_music.Album = field.NewString(tableName, "album")
	_music.CoverURL = field.NewString(tableName, "cover_url")
	_music.MusicURL = field.NewString(tableName, "music_url")
	_music.Duration = field.NewInt32(tableName, "duration")
	_music.UseCount = field.NewInt32(tableName, "use_count")
	_music.Status = field.NewInt32(tableName, "status")
	_music.CreatedAt = field.NewTime(tableName, "created_at")
	_music.UpdatedAt = field.NewTime(tableName, "updated_at")

	_music.fillFieldMap()

	return _music
}

// music 音乐表
type music struct {
	musicDo musicDo

	ALL       field.Asterisk
	ID        field.Int64  // 音乐ID
	Name      field.String // 音乐名称
	Artist    field.String // 艺术家
	Album     field.String // 专辑
	CoverURL  field.String // 封面URL
	MusicURL  field.String // 音乐URL
	Duration  field.Int32  // 时长（秒）
	UseCount  field.Int32  // 使用次数
	Status    field.Int32  // 状态：1-正常，2-禁用
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (m music) Table(newTableName string) *music {
	m.musicDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m music) As(alias string) *music {
	m.musicDo.DO = *(m.musicDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *music) updateTableName(table string) *music {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.Name = field.NewString(table, "name")
	m.Artist = field.NewString(table, "artist")
	m.Album = field.NewString(table, "album")
	m.CoverURL = field.NewString(table, "cover_url")
	m.MusicURL = field.NewString(table, "music_url")
	m.Duration = field.NewInt32(table, "duration")
	m.UseCount = field.NewInt32(table, "use_count")
	m.Status = field.NewInt32(table, "status")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *music) WithContext(ctx context.Context) IMusicDo { return m.musicDo.WithContext(ctx) }

func (m music) TableName() string { return m.musicDo.TableName() }

func (m music) Alias() string { return m.musicDo.Alias() }

func (m music) Columns(cols ...field.Expr) gen.Columns { return m.musicDo.Columns(cols...) }

func (m *music) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *music) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 11)
	m.fieldMap["id"] = m.ID
	m.fieldMap["name"] = m.Name
	m.fieldMap["artist"] = m.Artist
	m.fieldMap["album"] = m.Album
	m.fieldMap["cover_url"] = m.CoverURL
	m.fieldMap["music_url"] = m.MusicURL
	m.fieldMap["duration"] = m.Duration
	m.fieldMap["use_count"] = m.UseCount
	m.fieldMap["status"] = m.Status
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m music) clone(db *gorm.DB) music {
	m.musicDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m music) replaceDB(db *gorm.DB) music {
	m.musicDo.ReplaceDB(db)
	return m
}

type musicDo struct{ gen.DO }

type IMusicDo interface {
	gen.SubQuery
	Debug() IMusicDo
	WithContext(ctx context.Context) IMusicDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMusicDo
	WriteDB() IMusicDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMusicDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMusicDo
	Not(conds ...gen.Condition) IMusicDo
	Or(conds ...gen.Condition) IMusicDo
	Select(conds ...field.Expr) IMusicDo
	Where(conds ...gen.Condition) IMusicDo
	Order(conds ...field.Expr) IMusicDo
	Distinct(cols ...field.Expr) IMusicDo
	Omit(cols ...field.Expr) IMusicDo
	Join(table schema.Tabler, on ...field.Expr) IMusicDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMusicDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMusicDo
	Group(cols ...field.Expr) IMusicDo
	Having(conds ...gen.Condition) IMusicDo
	Limit(limit int) IMusicDo
	Offset(offset int) IMusicDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMusicDo
	Unscoped() IMusicDo
	Create(values ...*model.Music) error
	CreateInBatches(values []*model.Music, batchSize int) error
	Save(values ...*model.Music) error
	First() (*model.Music, error)
	Take() (*model.Music, error)
	Last() (*model.Music, error)
	Find() ([]*model.Music, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Music, err error)
	FindInBatches(result *[]*model.Music, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Music) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMusicDo
	Assign(attrs ...field.AssignExpr) IMusicDo
	Joins(fields ...field.RelationField) IMusicDo
	Preload(fields ...field.RelationField) IMusicDo
	FirstOrInit() (*model.Music, error)
	FirstOrCreate() (*model.Music, error)
	FindByPage(offset int, limit int) (result []*model.Music, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMusicDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m musicDo) Debug() IMusicDo {
	return m.withDO(m.DO.Debug())
}

func (m musicDo) WithContext(ctx context.Context) IMusicDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m musicDo) ReadDB() IMusicDo {
	return m.Clauses(dbresolver.Read)
}

func (m musicDo) WriteDB() IMusicDo {
	return m.Clauses(dbresolver.Write)
}

func (m musicDo) Session(config *gorm.Session) IMusicDo {
	return m.withDO(m.DO.Session(config))
}

func (m musicDo) Clauses(conds ...clause.Expression) IMusicDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m musicDo) Returning(value interface{}, columns ...string) IMusicDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m musicDo) Not(conds ...gen.Condition) IMusicDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m musicDo) Or(conds ...gen.Condition) IMusicDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m musicDo) Select(conds ...field.Expr) IMusicDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m musicDo) Where(conds ...gen.Condition) IMusicDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m musicDo) Order(conds ...field.Expr) IMusicDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m musicDo) Distinct(cols ...field.Expr) IMusicDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m musicDo) Omit(cols ...field.Expr) IMusicDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m musicDo) Join(table schema.Tabler, on ...field.Expr) IMusicDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m musicDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMusicDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m musicDo) RightJoin(table schema.Tabler, on ...field.Expr) IMusicDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m musicDo) Group(cols ...field.Expr) IMusicDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m musicDo) Having(conds ...gen.Condition) IMusicDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m musicDo) Limit(limit int) IMusicDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m musicDo) Offset(offset int) IMusicDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m musicDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMusicDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m musicDo) Unscoped() IMusicDo {
	return m.withDO(m.DO.Unscoped())
}

func (m musicDo) Create(values ...*model.Music) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m musicDo) CreateInBatches(values []*model.Music, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m musicDo) Save(values ...*model.Music) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m musicDo) First() (*model.Music, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Music), nil
	}
}

func (m musicDo) Take() (*model.Music, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Music), nil
	}
}

func (m musicDo) Last() (*model.Music, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Music), nil
	}
}

func (m musicDo) Find() ([]*model.Music, error) {
	result, err := m.DO.Find()
	return result.([]*model.Music), err
}

func (m musicDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Music, err error) {
	buf := make([]*model.Music, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m musicDo) FindInBatches(result *[]*model.Music, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m musicDo) Attrs(attrs ...field.AssignExpr) IMusicDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m musicDo) Assign(attrs ...field.AssignExpr) IMusicDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m musicDo) Joins(fields ...field.RelationField) IMusicDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m musicDo) Preload(fields ...field.RelationField) IMusicDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m musicDo) FirstOrInit() (*model.Music, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Music), nil
	}
}

func (m musicDo) FirstOrCreate() (*model.Music, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Music), nil
	}
}

func (m musicDo) FindByPage(offset int, limit int) (result []*model.Music, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m musicDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m musicDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m musicDo) Delete(models ...*model.Music) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *musicDo) withDO(do gen.Dao) *musicDo {
	m.DO = *do.(*gen.DO)
	return m
}
