// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"flashvid-platform/internal/model"
)

func newVideoTopic(db *gorm.DB, opts ...gen.DOOption) videoTopic {
	_videoTopic := videoTopic{}

	_videoTopic.videoTopicDo.UseDB(db, opts...)
	_videoTopic.videoTopicDo.UseModel(&model.VideoTopic{})

	tableName := _videoTopic.videoTopicDo.TableName()
	_videoTopic.ALL = field.NewAsterisk(tableName)
	_videoTopic.ID = field.NewInt64(tableName, "id")
	_videoTopic.VideoID = field.NewInt64(tableName, "video_id")
	_videoTopic.TopicID = field.NewInt64(tableName, "topic_id")
	_videoTopic.CreatedAt = field.NewTime(tableName, "created_at")

	_videoTopic.fillFieldMap()

	return _videoTopic
}

// videoTopic 视频话题关联表
type videoTopic struct {
	videoTopicDo videoTopicDo

	ALL       field.Asterisk
	ID        field.Int64 // ID
	VideoID   field.Int64 // 视频ID
	TopicID   field.Int64 // 话题ID
	CreatedAt field.Time  // 创建时间

	fieldMap map[string]field.Expr
}

func (v videoTopic) Table(newTableName string) *videoTopic {
	v.videoTopicDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v videoTopic) As(alias string) *videoTopic {
	v.videoTopicDo.DO = *(v.videoTopicDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *videoTopic) updateTableName(table string) *videoTopic {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.VideoID = field.NewInt64(table, "video_id")
	v.TopicID = field.NewInt64(table, "topic_id")
	v.CreatedAt = field.NewTime(table, "created_at")

	v.fillFieldMap()

	return v
}

func (v *videoTopic) WithContext(ctx context.Context) IVideoTopicDo {
	return v.videoTopicDo.WithContext(ctx)
}

func (v videoTopic) TableName() string { return v.videoTopicDo.TableName() }

func (v videoTopic) Alias() string { return v.videoTopicDo.Alias() }

func (v videoTopic) Columns(cols ...field.Expr) gen.Columns { return v.videoTopicDo.Columns(cols...) }

func (v *videoTopic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *videoTopic) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 4)
	v.fieldMap["id"] = v.ID
	v.fieldMap["video_id"] = v.VideoID
	v.fieldMap["topic_id"] = v.TopicID
	v.fieldMap["created_at"] = v.CreatedAt
}

func (v videoTopic) clone(db *gorm.DB) videoTopic {
	v.videoTopicDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v videoTopic) replaceDB(db *gorm.DB) videoTopic {
	v.videoTopicDo.ReplaceDB(db)
	return v
}

type videoTopicDo struct{ gen.DO }

type IVideoTopicDo interface {
	gen.SubQuery
	Debug() IVideoTopicDo
	WithContext(ctx context.Context) IVideoTopicDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVideoTopicDo
	WriteDB() IVideoTopicDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVideoTopicDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVideoTopicDo
	Not(conds ...gen.Condition) IVideoTopicDo
	Or(conds ...gen.Condition) IVideoTopicDo
	Select(conds ...field.Expr) IVideoTopicDo
	Where(conds ...gen.Condition) IVideoTopicDo
	Order(conds ...field.Expr) IVideoTopicDo
	Distinct(cols ...field.Expr) IVideoTopicDo
	Omit(cols ...field.Expr) IVideoTopicDo
	Join(table schema.Tabler, on ...field.Expr) IVideoTopicDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVideoTopicDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVideoTopicDo
	Group(cols ...field.Expr) IVideoTopicDo
	Having(conds ...gen.Condition) IVideoTopicDo
	Limit(limit int) IVideoTopicDo
	Offset(offset int) IVideoTopicDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVideoTopicDo
	Unscoped() IVideoTopicDo
	Create(values ...*model.VideoTopic) error
	CreateInBatches(values []*model.VideoTopic, batchSize int) error
	Save(values ...*model.VideoTopic) error
	First() (*model.VideoTopic, error)
	Take() (*model.VideoTopic, error)
	Last() (*model.VideoTopic, error)
	Find() ([]*model.VideoTopic, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VideoTopic, err error)
	FindInBatches(result *[]*model.VideoTopic, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.VideoTopic) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVideoTopicDo
	Assign(attrs ...field.AssignExpr) IVideoTopicDo
	Joins(fields ...field.RelationField) IVideoTopicDo
	Preload(fields ...field.RelationField) IVideoTopicDo
	FirstOrInit() (*model.VideoTopic, error)
	FirstOrCreate() (*model.VideoTopic, error)
	FindByPage(offset int, limit int) (result []*model.VideoTopic, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVideoTopicDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v videoTopicDo) Debug() IVideoTopicDo {
	return v.withDO(v.DO.Debug())
}

func (v videoTopicDo) WithContext(ctx context.Context) IVideoTopicDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v videoTopicDo) ReadDB() IVideoTopicDo {
	return v.Clauses(dbresolver.Read)
}

func (v videoTopicDo) WriteDB() IVideoTopicDo {
	return v.Clauses(dbresolver.Write)
}

func (v videoTopicDo) Session(config *gorm.Session) IVideoTopicDo {
	return v.withDO(v.DO.Session(config))
}

func (v videoTopicDo) Clauses(conds ...clause.Expression) IVideoTopicDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v videoTopicDo) Returning(value interface{}, columns ...string) IVideoTopicDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v videoTopicDo) Not(conds ...gen.Condition) IVideoTopicDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v videoTopicDo) Or(conds ...gen.Condition) IVideoTopicDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v videoTopicDo) Select(conds ...field.Expr) IVideoTopicDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v videoTopicDo) Where(conds ...gen.Condition) IVideoTopicDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v videoTopicDo) Order(conds ...field.Expr) IVideoTopicDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v videoTopicDo) Distinct(cols ...field.Expr) IVideoTopicDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v videoTopicDo) Omit(cols ...field.Expr) IVideoTopicDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v videoTopicDo) Join(table schema.Tabler, on ...field.Expr) IVideoTopicDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v videoTopicDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVideoTopicDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v videoTopicDo) RightJoin(table schema.Tabler, on ...field.Expr) IVideoTopicDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v videoTopicDo) Group(cols ...field.Expr) IVideoTopicDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v videoTopicDo) Having(conds ...gen.Condition) IVideoTopicDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v videoTopicDo) Limit(limit int) IVideoTopicDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v videoTopicDo) Offset(offset int) IVideoTopicDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v videoTopicDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVideoTopicDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v videoTopicDo) Unscoped() IVideoTopicDo {
	return v.withDO(v.DO.Unscoped())
}

func (v videoTopicDo) Create(values ...*model.VideoTopic) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v videoTopicDo) CreateInBatches(values []*model.VideoTopic, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v videoTopicDo) Save(values ...*model.VideoTopic) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v videoTopicDo) First() (*model.VideoTopic, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTopic), nil
	}
}

func (v videoTopicDo) Take() (*model.VideoTopic, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTopic), nil
	}
}

func (v videoTopicDo) Last() (*model.VideoTopic, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTopic), nil
	}
}

func (v videoTopicDo) Find() ([]*model.VideoTopic, error) {
	result, err := v.DO.Find()
	return result.([]*model.VideoTopic), err
}

func (v videoTopicDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VideoTopic, err error) {
	buf := make([]*model.VideoTopic, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v videoTopicDo) FindInBatches(result *[]*model.VideoTopic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v videoTopicDo) Attrs(attrs ...field.AssignExpr) IVideoTopicDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v videoTopicDo) Assign(attrs ...field.AssignExpr) IVideoTopicDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v videoTopicDo) Joins(fields ...field.RelationField) IVideoTopicDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v videoTopicDo) Preload(fields ...field.RelationField) IVideoTopicDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v videoTopicDo) FirstOrInit() (*model.VideoTopic, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTopic), nil
	}
}

func (v videoTopicDo) FirstOrCreate() (*model.VideoTopic, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoTopic), nil
	}
}

func (v videoTopicDo) FindByPage(offset int, limit int) (result []*model.VideoTopic, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v videoTopicDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v videoTopicDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v videoTopicDo) Delete(models ...*model.VideoTopic) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *videoTopicDo) withDO(do gen.Dao) *videoTopicDo {
	v.DO = *do.(*gen.DO)
	return v
}
