// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameComment = "comments"

// Comment 评论表
type Comment struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:评论ID" json:"id"`                      // 评论ID
	VideoID       int64          `gorm:"column:video_id;not null;comment:视频ID" json:"video_id"`                               // 视频ID
	UserID        int64          `gorm:"column:user_id;not null;comment:评论者ID" json:"user_id"`                                // 评论者ID
	ParentID      int64          `gorm:"column:parent_id;comment:父评论ID，0为一级评论" json:"parent_id"`                              // 父评论ID，0为一级评论
	ReplyToUserID int64          `gorm:"column:reply_to_user_id;comment:回复的用户ID" json:"reply_to_user_id"`                     // 回复的用户ID
	Content       string         `gorm:"column:content;not null;comment:评论内容" json:"content"`                                 // 评论内容
	LikeCount     int32          `gorm:"column:like_count;comment:点赞数" json:"like_count"`                                     // 点赞数
	ReplyCount    int32          `gorm:"column:reply_count;comment:回复数" json:"reply_count"`                                   // 回复数
	Status        int32          `gorm:"column:status;default:1;comment:状态：1-正常，2-已删除，3-审核中" json:"status"`                   // 状态：1-正常，2-已删除，3-审核中
	IPAddress     string         `gorm:"column:ip_address;comment:评论IP" json:"ip_address"`                                    // 评论IP
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
