// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFollow = "follows"

// Follow 关注关系表
type Follow struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                        // ID
	FollowerID  int64          `gorm:"column:follower_id;not null;comment:粉丝ID" json:"follower_id"`                         // 粉丝ID
	FollowingID int64          `gorm:"column:following_id;not null;comment:被关注者ID" json:"following_id"`                     // 被关注者ID
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
