// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLike = "likes"

// Like 点赞表
type Like struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                        // ID
	UserID     int64          `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                 // 用户ID
	TargetType int32          `gorm:"column:target_type;not null;comment:点赞类型：1-视频，2-评论" json:"target_type"`               // 点赞类型：1-视频，2-评论
	TargetID   int64          `gorm:"column:target_id;not null;comment:目标ID" json:"target_id"`                             // 目标ID
	CreatedAt  time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName Like's table name
func (*Like) TableName() string {
	return TableNameLike
}
