// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTopic = "topics"

// Topic 话题表
type Topic struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:话题ID" json:"id"`                      // 话题ID
	Name        string    `gorm:"column:name;not null;comment:话题名称" json:"name"`                                       // 话题名称
	Description string    `gorm:"column:description;comment:话题描述" json:"description"`                                  // 话题描述
	CoverURL    string    `gorm:"column:cover_url;comment:话题封面" json:"cover_url"`                                      // 话题封面
	ViewCount   int64     `gorm:"column:view_count;comment:浏览量" json:"view_count"`                                     // 浏览量
	VideoCount  int32     `gorm:"column:video_count;comment:视频数" json:"video_count"`                                   // 视频数
	Status      int32     `gorm:"column:status;default:1;comment:状态：1-正常，2-禁用" json:"status"`                          // 状态：1-正常，2-禁用
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Topic's table name
func (*Topic) TableName() string {
	return TableNameTopic
}
