// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	Comment       *comment
	Conversation  *conversation
	Favorite      *favorite
	Follow        *follow
	Like          *like
	LoginLog      *loginLog
	Message       *message
	Music         *music
	Playlist      *playlist
	PlaylistVideo *playlistVideo
	Topic         *topic
	User          *user
	Video         *video
	VideoTopic    *videoTopic
	ViewHistory   *viewHistory
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Comment = &Q.Comment
	Conversation = &Q.Conversation
	Favorite = &Q.Favorite
	Follow = &Q.Follow
	Like = &Q.Like
	LoginLog = &Q.LoginLog
	Message = &Q.Message
	Music = &Q.Music
	Playlist = &Q.Playlist
	PlaylistVideo = &Q.PlaylistVideo
	Topic = &Q.Topic
	User = &Q.User
	Video = &Q.Video
	VideoTopic = &Q.VideoTopic
	ViewHistory = &Q.ViewHistory
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		Comment:       newComment(db, opts...),
		Conversation:  newConversation(db, opts...),
		Favorite:      newFavorite(db, opts...),
		Follow:        newFollow(db, opts...),
		Like:          newLike(db, opts...),
		LoginLog:      newLoginLog(db, opts...),
		Message:       newMessage(db, opts...),
		Music:         newMusic(db, opts...),
		Playlist:      newPlaylist(db, opts...),
		PlaylistVideo: newPlaylistVideo(db, opts...),
		Topic:         newTopic(db, opts...),
		User:          newUser(db, opts...),
		Video:         newVideo(db, opts...),
		VideoTopic:    newVideoTopic(db, opts...),
		ViewHistory:   newViewHistory(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Comment       comment
	Conversation  conversation
	Favorite      favorite
	Follow        follow
	Like          like
	LoginLog      loginLog
	Message       message
	Music         music
	Playlist      playlist
	PlaylistVideo playlistVideo
	Topic         topic
	User          user
	Video         video
	VideoTopic    videoTopic
	ViewHistory   viewHistory
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Comment:       q.Comment.clone(db),
		Conversation:  q.Conversation.clone(db),
		Favorite:      q.Favorite.clone(db),
		Follow:        q.Follow.clone(db),
		Like:          q.Like.clone(db),
		LoginLog:      q.LoginLog.clone(db),
		Message:       q.Message.clone(db),
		Music:         q.Music.clone(db),
		Playlist:      q.Playlist.clone(db),
		PlaylistVideo: q.PlaylistVideo.clone(db),
		Topic:         q.Topic.clone(db),
		User:          q.User.clone(db),
		Video:         q.Video.clone(db),
		VideoTopic:    q.VideoTopic.clone(db),
		ViewHistory:   q.ViewHistory.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Comment:       q.Comment.replaceDB(db),
		Conversation:  q.Conversation.replaceDB(db),
		Favorite:      q.Favorite.replaceDB(db),
		Follow:        q.Follow.replaceDB(db),
		Like:          q.Like.replaceDB(db),
		LoginLog:      q.LoginLog.replaceDB(db),
		Message:       q.Message.replaceDB(db),
		Music:         q.Music.replaceDB(db),
		Playlist:      q.Playlist.replaceDB(db),
		PlaylistVideo: q.PlaylistVideo.replaceDB(db),
		Topic:         q.Topic.replaceDB(db),
		User:          q.User.replaceDB(db),
		Video:         q.Video.replaceDB(db),
		VideoTopic:    q.VideoTopic.replaceDB(db),
		ViewHistory:   q.ViewHistory.replaceDB(db),
	}
}

type queryCtx struct {
	Comment       ICommentDo
	Conversation  IConversationDo
	Favorite      IFavoriteDo
	Follow        IFollowDo
	Like          ILikeDo
	LoginLog      ILoginLogDo
	Message       IMessageDo
	Music         IMusicDo
	Playlist      IPlaylistDo
	PlaylistVideo IPlaylistVideoDo
	Topic         ITopicDo
	User          IUserDo
	Video         IVideoDo
	VideoTopic    IVideoTopicDo
	ViewHistory   IViewHistoryDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Comment:       q.Comment.WithContext(ctx),
		Conversation:  q.Conversation.WithContext(ctx),
		Favorite:      q.Favorite.WithContext(ctx),
		Follow:        q.Follow.WithContext(ctx),
		Like:          q.Like.WithContext(ctx),
		LoginLog:      q.LoginLog.WithContext(ctx),
		Message:       q.Message.WithContext(ctx),
		Music:         q.Music.WithContext(ctx),
		Playlist:      q.Playlist.WithContext(ctx),
		PlaylistVideo: q.PlaylistVideo.WithContext(ctx),
		Topic:         q.Topic.WithContext(ctx),
		User:          q.User.WithContext(ctx),
		Video:         q.Video.WithContext(ctx),
		VideoTopic:    q.VideoTopic.WithContext(ctx),
		ViewHistory:   q.ViewHistory.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
