// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"flashvid-platform-gin/internal/model"
)

func newPlaylistVideo(db *gorm.DB, opts ...gen.DOOption) playlistVideo {
	_playlistVideo := playlistVideo{}

	_playlistVideo.playlistVideoDo.UseDB(db, opts...)
	_playlistVideo.playlistVideoDo.UseModel(&model.PlaylistVideo{})

	tableName := _playlistVideo.playlistVideoDo.TableName()
	_playlistVideo.ALL = field.NewAsterisk(tableName)
	_playlistVideo.ID = field.NewInt64(tableName, "id")
	_playlistVideo.PlaylistID = field.NewInt64(tableName, "playlist_id")
	_playlistVideo.VideoID = field.NewInt64(tableName, "video_id")
	_playlistVideo.SortOrder = field.NewInt32(tableName, "sort_order")
	_playlistVideo.CreatedAt = field.NewTime(tableName, "created_at")

	_playlistVideo.fillFieldMap()

	return _playlistVideo
}

// playlistVideo 播放列表视频关联表
type playlistVideo struct {
	playlistVideoDo playlistVideoDo

	ALL        field.Asterisk
	ID         field.Int64 // ID
	PlaylistID field.Int64 // 播放列表ID
	VideoID    field.Int64 // 视频ID
	SortOrder  field.Int32 // 排序
	CreatedAt  field.Time  // 创建时间

	fieldMap map[string]field.Expr
}

func (p playlistVideo) Table(newTableName string) *playlistVideo {
	p.playlistVideoDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p playlistVideo) As(alias string) *playlistVideo {
	p.playlistVideoDo.DO = *(p.playlistVideoDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *playlistVideo) updateTableName(table string) *playlistVideo {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.PlaylistID = field.NewInt64(table, "playlist_id")
	p.VideoID = field.NewInt64(table, "video_id")
	p.SortOrder = field.NewInt32(table, "sort_order")
	p.CreatedAt = field.NewTime(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *playlistVideo) WithContext(ctx context.Context) IPlaylistVideoDo {
	return p.playlistVideoDo.WithContext(ctx)
}

func (p playlistVideo) TableName() string { return p.playlistVideoDo.TableName() }

func (p playlistVideo) Alias() string { return p.playlistVideoDo.Alias() }

func (p playlistVideo) Columns(cols ...field.Expr) gen.Columns {
	return p.playlistVideoDo.Columns(cols...)
}

func (p *playlistVideo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *playlistVideo) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["id"] = p.ID
	p.fieldMap["playlist_id"] = p.PlaylistID
	p.fieldMap["video_id"] = p.VideoID
	p.fieldMap["sort_order"] = p.SortOrder
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p playlistVideo) clone(db *gorm.DB) playlistVideo {
	p.playlistVideoDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p playlistVideo) replaceDB(db *gorm.DB) playlistVideo {
	p.playlistVideoDo.ReplaceDB(db)
	return p
}

type playlistVideoDo struct{ gen.DO }

type IPlaylistVideoDo interface {
	gen.SubQuery
	Debug() IPlaylistVideoDo
	WithContext(ctx context.Context) IPlaylistVideoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPlaylistVideoDo
	WriteDB() IPlaylistVideoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPlaylistVideoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPlaylistVideoDo
	Not(conds ...gen.Condition) IPlaylistVideoDo
	Or(conds ...gen.Condition) IPlaylistVideoDo
	Select(conds ...field.Expr) IPlaylistVideoDo
	Where(conds ...gen.Condition) IPlaylistVideoDo
	Order(conds ...field.Expr) IPlaylistVideoDo
	Distinct(cols ...field.Expr) IPlaylistVideoDo
	Omit(cols ...field.Expr) IPlaylistVideoDo
	Join(table schema.Tabler, on ...field.Expr) IPlaylistVideoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPlaylistVideoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPlaylistVideoDo
	Group(cols ...field.Expr) IPlaylistVideoDo
	Having(conds ...gen.Condition) IPlaylistVideoDo
	Limit(limit int) IPlaylistVideoDo
	Offset(offset int) IPlaylistVideoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPlaylistVideoDo
	Unscoped() IPlaylistVideoDo
	Create(values ...*model.PlaylistVideo) error
	CreateInBatches(values []*model.PlaylistVideo, batchSize int) error
	Save(values ...*model.PlaylistVideo) error
	First() (*model.PlaylistVideo, error)
	Take() (*model.PlaylistVideo, error)
	Last() (*model.PlaylistVideo, error)
	Find() ([]*model.PlaylistVideo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PlaylistVideo, err error)
	FindInBatches(result *[]*model.PlaylistVideo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PlaylistVideo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPlaylistVideoDo
	Assign(attrs ...field.AssignExpr) IPlaylistVideoDo
	Joins(fields ...field.RelationField) IPlaylistVideoDo
	Preload(fields ...field.RelationField) IPlaylistVideoDo
	FirstOrInit() (*model.PlaylistVideo, error)
	FirstOrCreate() (*model.PlaylistVideo, error)
	FindByPage(offset int, limit int) (result []*model.PlaylistVideo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPlaylistVideoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p playlistVideoDo) Debug() IPlaylistVideoDo {
	return p.withDO(p.DO.Debug())
}

func (p playlistVideoDo) WithContext(ctx context.Context) IPlaylistVideoDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p playlistVideoDo) ReadDB() IPlaylistVideoDo {
	return p.Clauses(dbresolver.Read)
}

func (p playlistVideoDo) WriteDB() IPlaylistVideoDo {
	return p.Clauses(dbresolver.Write)
}

func (p playlistVideoDo) Session(config *gorm.Session) IPlaylistVideoDo {
	return p.withDO(p.DO.Session(config))
}

func (p playlistVideoDo) Clauses(conds ...clause.Expression) IPlaylistVideoDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p playlistVideoDo) Returning(value interface{}, columns ...string) IPlaylistVideoDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p playlistVideoDo) Not(conds ...gen.Condition) IPlaylistVideoDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p playlistVideoDo) Or(conds ...gen.Condition) IPlaylistVideoDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p playlistVideoDo) Select(conds ...field.Expr) IPlaylistVideoDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p playlistVideoDo) Where(conds ...gen.Condition) IPlaylistVideoDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p playlistVideoDo) Order(conds ...field.Expr) IPlaylistVideoDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p playlistVideoDo) Distinct(cols ...field.Expr) IPlaylistVideoDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p playlistVideoDo) Omit(cols ...field.Expr) IPlaylistVideoDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p playlistVideoDo) Join(table schema.Tabler, on ...field.Expr) IPlaylistVideoDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p playlistVideoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPlaylistVideoDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p playlistVideoDo) RightJoin(table schema.Tabler, on ...field.Expr) IPlaylistVideoDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p playlistVideoDo) Group(cols ...field.Expr) IPlaylistVideoDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p playlistVideoDo) Having(conds ...gen.Condition) IPlaylistVideoDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p playlistVideoDo) Limit(limit int) IPlaylistVideoDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p playlistVideoDo) Offset(offset int) IPlaylistVideoDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p playlistVideoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPlaylistVideoDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p playlistVideoDo) Unscoped() IPlaylistVideoDo {
	return p.withDO(p.DO.Unscoped())
}

func (p playlistVideoDo) Create(values ...*model.PlaylistVideo) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p playlistVideoDo) CreateInBatches(values []*model.PlaylistVideo, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p playlistVideoDo) Save(values ...*model.PlaylistVideo) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p playlistVideoDo) First() (*model.PlaylistVideo, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaylistVideo), nil
	}
}

func (p playlistVideoDo) Take() (*model.PlaylistVideo, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaylistVideo), nil
	}
}

func (p playlistVideoDo) Last() (*model.PlaylistVideo, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaylistVideo), nil
	}
}

func (p playlistVideoDo) Find() ([]*model.PlaylistVideo, error) {
	result, err := p.DO.Find()
	return result.([]*model.PlaylistVideo), err
}

func (p playlistVideoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PlaylistVideo, err error) {
	buf := make([]*model.PlaylistVideo, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p playlistVideoDo) FindInBatches(result *[]*model.PlaylistVideo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p playlistVideoDo) Attrs(attrs ...field.AssignExpr) IPlaylistVideoDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p playlistVideoDo) Assign(attrs ...field.AssignExpr) IPlaylistVideoDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p playlistVideoDo) Joins(fields ...field.RelationField) IPlaylistVideoDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p playlistVideoDo) Preload(fields ...field.RelationField) IPlaylistVideoDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p playlistVideoDo) FirstOrInit() (*model.PlaylistVideo, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaylistVideo), nil
	}
}

func (p playlistVideoDo) FirstOrCreate() (*model.PlaylistVideo, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaylistVideo), nil
	}
}

func (p playlistVideoDo) FindByPage(offset int, limit int) (result []*model.PlaylistVideo, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p playlistVideoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p playlistVideoDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p playlistVideoDo) Delete(models ...*model.PlaylistVideo) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *playlistVideoDo) withDO(do gen.Dao) *playlistVideoDo {
	p.DO = *do.(*gen.DO)
	return p
}
