// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"flashvid-platform-gin/internal/model"
)

func newViewHistory(db *gorm.DB, opts ...gen.DOOption) viewHistory {
	_viewHistory := viewHistory{}

	_viewHistory.viewHistoryDo.UseDB(db, opts...)
	_viewHistory.viewHistoryDo.UseModel(&model.ViewHistory{})

	tableName := _viewHistory.viewHistoryDo.TableName()
	_viewHistory.ALL = field.NewAsterisk(tableName)
	_viewHistory.ID = field.NewInt64(tableName, "id")
	_viewHistory.UserID = field.NewInt64(tableName, "user_id")
	_viewHistory.VideoID = field.NewInt64(tableName, "video_id")
	_viewHistory.Duration = field.NewInt32(tableName, "duration")
	_viewHistory.Progress = field.NewFloat64(tableName, "progress")
	_viewHistory.CreatedAt = field.NewTime(tableName, "created_at")
	_viewHistory.UpdatedAt = field.NewTime(tableName, "updated_at")

	_viewHistory.fillFieldMap()

	return _viewHistory
}

// viewHistory 播放历史表
type viewHistory struct {
	viewHistoryDo viewHistoryDo

	ALL       field.Asterisk
	ID        field.Int64   // ID
	UserID    field.Int64   // 用户ID
	VideoID   field.Int64   // 视频ID
	Duration  field.Int32   // 观看时长（秒）
	Progress  field.Float64 // 观看进度（百分比）
	CreatedAt field.Time    // 创建时间
	UpdatedAt field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (v viewHistory) Table(newTableName string) *viewHistory {
	v.viewHistoryDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v viewHistory) As(alias string) *viewHistory {
	v.viewHistoryDo.DO = *(v.viewHistoryDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *viewHistory) updateTableName(table string) *viewHistory {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.UserID = field.NewInt64(table, "user_id")
	v.VideoID = field.NewInt64(table, "video_id")
	v.Duration = field.NewInt32(table, "duration")
	v.Progress = field.NewFloat64(table, "progress")
	v.CreatedAt = field.NewTime(table, "created_at")
	v.UpdatedAt = field.NewTime(table, "updated_at")

	v.fillFieldMap()

	return v
}

func (v *viewHistory) WithContext(ctx context.Context) IViewHistoryDo {
	return v.viewHistoryDo.WithContext(ctx)
}

func (v viewHistory) TableName() string { return v.viewHistoryDo.TableName() }

func (v viewHistory) Alias() string { return v.viewHistoryDo.Alias() }

func (v viewHistory) Columns(cols ...field.Expr) gen.Columns { return v.viewHistoryDo.Columns(cols...) }

func (v *viewHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *viewHistory) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 7)
	v.fieldMap["id"] = v.ID
	v.fieldMap["user_id"] = v.UserID
	v.fieldMap["video_id"] = v.VideoID
	v.fieldMap["duration"] = v.Duration
	v.fieldMap["progress"] = v.Progress
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
}

func (v viewHistory) clone(db *gorm.DB) viewHistory {
	v.viewHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v viewHistory) replaceDB(db *gorm.DB) viewHistory {
	v.viewHistoryDo.ReplaceDB(db)
	return v
}

type viewHistoryDo struct{ gen.DO }

type IViewHistoryDo interface {
	gen.SubQuery
	Debug() IViewHistoryDo
	WithContext(ctx context.Context) IViewHistoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IViewHistoryDo
	WriteDB() IViewHistoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IViewHistoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IViewHistoryDo
	Not(conds ...gen.Condition) IViewHistoryDo
	Or(conds ...gen.Condition) IViewHistoryDo
	Select(conds ...field.Expr) IViewHistoryDo
	Where(conds ...gen.Condition) IViewHistoryDo
	Order(conds ...field.Expr) IViewHistoryDo
	Distinct(cols ...field.Expr) IViewHistoryDo
	Omit(cols ...field.Expr) IViewHistoryDo
	Join(table schema.Tabler, on ...field.Expr) IViewHistoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IViewHistoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IViewHistoryDo
	Group(cols ...field.Expr) IViewHistoryDo
	Having(conds ...gen.Condition) IViewHistoryDo
	Limit(limit int) IViewHistoryDo
	Offset(offset int) IViewHistoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IViewHistoryDo
	Unscoped() IViewHistoryDo
	Create(values ...*model.ViewHistory) error
	CreateInBatches(values []*model.ViewHistory, batchSize int) error
	Save(values ...*model.ViewHistory) error
	First() (*model.ViewHistory, error)
	Take() (*model.ViewHistory, error)
	Last() (*model.ViewHistory, error)
	Find() ([]*model.ViewHistory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ViewHistory, err error)
	FindInBatches(result *[]*model.ViewHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ViewHistory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IViewHistoryDo
	Assign(attrs ...field.AssignExpr) IViewHistoryDo
	Joins(fields ...field.RelationField) IViewHistoryDo
	Preload(fields ...field.RelationField) IViewHistoryDo
	FirstOrInit() (*model.ViewHistory, error)
	FirstOrCreate() (*model.ViewHistory, error)
	FindByPage(offset int, limit int) (result []*model.ViewHistory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IViewHistoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v viewHistoryDo) Debug() IViewHistoryDo {
	return v.withDO(v.DO.Debug())
}

func (v viewHistoryDo) WithContext(ctx context.Context) IViewHistoryDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v viewHistoryDo) ReadDB() IViewHistoryDo {
	return v.Clauses(dbresolver.Read)
}

func (v viewHistoryDo) WriteDB() IViewHistoryDo {
	return v.Clauses(dbresolver.Write)
}

func (v viewHistoryDo) Session(config *gorm.Session) IViewHistoryDo {
	return v.withDO(v.DO.Session(config))
}

func (v viewHistoryDo) Clauses(conds ...clause.Expression) IViewHistoryDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v viewHistoryDo) Returning(value interface{}, columns ...string) IViewHistoryDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v viewHistoryDo) Not(conds ...gen.Condition) IViewHistoryDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v viewHistoryDo) Or(conds ...gen.Condition) IViewHistoryDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v viewHistoryDo) Select(conds ...field.Expr) IViewHistoryDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v viewHistoryDo) Where(conds ...gen.Condition) IViewHistoryDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v viewHistoryDo) Order(conds ...field.Expr) IViewHistoryDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v viewHistoryDo) Distinct(cols ...field.Expr) IViewHistoryDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v viewHistoryDo) Omit(cols ...field.Expr) IViewHistoryDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v viewHistoryDo) Join(table schema.Tabler, on ...field.Expr) IViewHistoryDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v viewHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IViewHistoryDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v viewHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IViewHistoryDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v viewHistoryDo) Group(cols ...field.Expr) IViewHistoryDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v viewHistoryDo) Having(conds ...gen.Condition) IViewHistoryDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v viewHistoryDo) Limit(limit int) IViewHistoryDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v viewHistoryDo) Offset(offset int) IViewHistoryDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v viewHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IViewHistoryDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v viewHistoryDo) Unscoped() IViewHistoryDo {
	return v.withDO(v.DO.Unscoped())
}

func (v viewHistoryDo) Create(values ...*model.ViewHistory) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v viewHistoryDo) CreateInBatches(values []*model.ViewHistory, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v viewHistoryDo) Save(values ...*model.ViewHistory) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v viewHistoryDo) First() (*model.ViewHistory, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ViewHistory), nil
	}
}

func (v viewHistoryDo) Take() (*model.ViewHistory, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ViewHistory), nil
	}
}

func (v viewHistoryDo) Last() (*model.ViewHistory, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ViewHistory), nil
	}
}

func (v viewHistoryDo) Find() ([]*model.ViewHistory, error) {
	result, err := v.DO.Find()
	return result.([]*model.ViewHistory), err
}

func (v viewHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ViewHistory, err error) {
	buf := make([]*model.ViewHistory, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v viewHistoryDo) FindInBatches(result *[]*model.ViewHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v viewHistoryDo) Attrs(attrs ...field.AssignExpr) IViewHistoryDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v viewHistoryDo) Assign(attrs ...field.AssignExpr) IViewHistoryDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v viewHistoryDo) Joins(fields ...field.RelationField) IViewHistoryDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v viewHistoryDo) Preload(fields ...field.RelationField) IViewHistoryDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v viewHistoryDo) FirstOrInit() (*model.ViewHistory, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ViewHistory), nil
	}
}

func (v viewHistoryDo) FirstOrCreate() (*model.ViewHistory, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ViewHistory), nil
	}
}

func (v viewHistoryDo) FindByPage(offset int, limit int) (result []*model.ViewHistory, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v viewHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v viewHistoryDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v viewHistoryDo) Delete(models ...*model.ViewHistory) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *viewHistoryDo) withDO(do gen.Dao) *viewHistoryDo {
	v.DO = *do.(*gen.DO)
	return v
}
