// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConversation = "conversations"

// Conversation 会话表
type Conversation struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:会话ID" json:"id"`         // 会话ID
	User1ID       int64     `gorm:"column:user1_id;not null;comment:较小的用户ID" json:"user1_id"`               // 较小的用户ID
	User2ID       int64     `gorm:"column:user2_id;not null;comment:较大的用户ID" json:"user2_id"`               // 较大的用户ID
	LastMessageID int64     `gorm:"column:last_message_id;comment:最后一条消息ID" json:"last_message_id"`         // 最后一条消息ID
	UnreadCount1  int32     `gorm:"column:unread_count1;not null;comment:user1的未读消息数" json:"unread_count1"` // user1的未读消息数
	UnreadCount2  int32     `gorm:"column:unread_count2;not null;comment:user2的未读消息数" json:"unread_count2"` // user2的未读消息数
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Conversation's table name
func (*Conversation) TableName() string {
	return TableNameConversation
}
