// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLoginLog = "login_logs"

// LoginLog 登录日志表
type LoginLog struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                        // ID
	UserID     int64     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                 // 用户ID
	IPAddress  string    `gorm:"column:ip_address;not null;comment:登录IP" json:"ip_address"`                           // 登录IP
	DeviceType string    `gorm:"column:device_type;comment:设备类型" json:"device_type"`                                  // 设备类型
	DeviceName string    `gorm:"column:device_name;comment:设备名称" json:"device_name"`                                  // 设备名称
	Os         string    `gorm:"column:os;comment:操作系统" json:"os"`                                                    // 操作系统
	Browser    string    `gorm:"column:browser;comment:浏览器" json:"browser"`                                           // 浏览器
	Location   string    `gorm:"column:location;comment:地理位置" json:"location"`                                        // 地理位置
	LoginType  int32     `gorm:"column:login_type;default:1;comment:登录方式：1-密码，2-短信，3-第三方" json:"login_type"`          // 登录方式：1-密码，2-短信，3-第三方
	Status     int32     `gorm:"column:status;default:1;comment:登录状态：1-成功，2-失败" json:"status"`                        // 登录状态：1-成功，2-失败
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName LoginLog's table name
func (*LoginLog) TableName() string {
	return TableNameLoginLog
}
