// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMessage = "messages"

// Message 消息表
type Message struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:消息ID" json:"id"`                      // 消息ID
	FromUserID  int64          `gorm:"column:from_user_id;not null;comment:发送者ID" json:"from_user_id"`                      // 发送者ID
	ToUserID    int64          `gorm:"column:to_user_id;not null;comment:接收者ID" json:"to_user_id"`                          // 接收者ID
	MessageType int32          `gorm:"column:message_type;not null;comment:消息类型：1-文本，2-图片，3-视频" json:"message_type"`        // 消息类型：1-文本，2-图片，3-视频
	Content     string         `gorm:"column:content;comment:消息内容" json:"content"`                                          // 消息内容
	MediaURL    string         `gorm:"column:media_url;comment:媒体文件URL" json:"media_url"`                                   // 媒体文件URL
	IsRead      int32          `gorm:"column:is_read;comment:是否已读：0-未读，1-已读" json:"is_read"`                                // 是否已读：0-未读，1-已读
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
