// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMusic = "music"

// Music 音乐表
type Music struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:音乐ID" json:"id"`                      // 音乐ID
	Name      string    `gorm:"column:name;not null;comment:音乐名称" json:"name"`                                       // 音乐名称
	Artist    string    `gorm:"column:artist;comment:艺术家" json:"artist"`                                             // 艺术家
	Album     string    `gorm:"column:album;comment:专辑" json:"album"`                                                // 专辑
	CoverURL  string    `gorm:"column:cover_url;comment:封面URL" json:"cover_url"`                                     // 封面URL
	MusicURL  string    `gorm:"column:music_url;not null;comment:音乐URL" json:"music_url"`                            // 音乐URL
	Duration  int32     `gorm:"column:duration;comment:时长（秒）" json:"duration"`                                       // 时长（秒）
	UseCount  int32     `gorm:"column:use_count;comment:使用次数" json:"use_count"`                                      // 使用次数
	Status    int32     `gorm:"column:status;default:1;comment:状态：1-正常，2-禁用" json:"status"`                          // 状态：1-正常，2-禁用
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Music's table name
func (*Music) TableName() string {
	return TableNameMusic
}
