// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNotification = "notifications"

// Notification 通知表
type Notification struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`
	UserID     int64     `gorm:"column:user_id;not null;comment:通知接收者ID" json:"user_id"`
	ActorID    int64     `gorm:"column:actor_id;not null;comment:触发者ID" json:"actor_id"`
	ActionType int32     `gorm:"column:action_type;not null;comment:1=关注 2=点赞视频 3=收藏视频 4=评论视频 5=回复评论" json:"action_type"`
	TargetType int32     `gorm:"column:target_type;not null;comment:1=用户 2=视频 3=评论" json:"target_type"`
	TargetID   int64     `gorm:"column:target_id;not null;comment:目标对象ID" json:"target_id"`
	Content    string    `gorm:"column:content;default:'';comment:附加内容（评论文本预览）" json:"content"`
	IsRead     int32     `gorm:"column:is_read;default:0;comment:0=未读 1=已读" json:"is_read"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`
}

// TableName Notification's table name
func (*Notification) TableName() string {
	return TableNameNotification
}
