// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User 用户表
type User struct {
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                      // 用户ID
	Username       string         `gorm:"column:username;not null;comment:用户名" json:"username"`                                // 用户名
	Password       string         `gorm:"column:password;not null;comment:密码（bcrypt加密）" json:"password"`                       // 密码（bcrypt加密）
	Nickname       string         `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`                                 // 昵称
	Avatar         string         `gorm:"column:avatar;comment:头像URL" json:"avatar"`                                           // 头像URL
	Phone          string         `gorm:"column:phone;comment:手机号" json:"phone"`                                               // 手机号
	Email          string         `gorm:"column:email;comment:邮箱" json:"email"`                                                // 邮箱
	Gender         int32          `gorm:"column:gender;comment:性别：0-未知，1-男，2-女" json:"gender"`                                 // 性别：0-未知，1-男，2-女
	Birthday       time.Time      `gorm:"column:birthday;comment:生日" json:"birthday"`                                          // 生日
	Bio            string         `gorm:"column:bio;comment:个人简介" json:"bio"`                                                  // 个人简介
	Province       string         `gorm:"column:province;comment:省份" json:"province"`                                          // 省份
	City           string         `gorm:"column:city;comment:城市" json:"city"`                                                  // 城市
	IPAddress      string         `gorm:"column:ip_address;comment:注册IP" json:"ip_address"`                                    // 注册IP
	Status         int32          `gorm:"column:status;default:1;comment:状态：1-正常，2-封禁" json:"status"`                          // 状态：1-正常，2-封禁
	FollowerCount  int32          `gorm:"column:follower_count;comment:粉丝数" json:"follower_count"`                             // 粉丝数
	FollowingCount int32          `gorm:"column:following_count;comment:关注数" json:"following_count"`                           // 关注数
	VideoCount     int32          `gorm:"column:video_count;comment:作品数" json:"video_count"`                                   // 作品数
	LikeCount      int32          `gorm:"column:like_count;comment:获赞数" json:"like_count"`                                     // 获赞数
	LastLoginAt    time.Time      `gorm:"column:last_login_at;comment:最后登录时间" json:"last_login_at"`                            // 最后登录时间
	CreatedAt      time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt      time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
