// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideoTopic = "video_topics"

// VideoTopic 视频话题关联表
type VideoTopic struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                        // ID
	VideoID   int64     `gorm:"column:video_id;not null;comment:视频ID" json:"video_id"`                               // 视频ID
	TopicID   int64     `gorm:"column:topic_id;not null;comment:话题ID" json:"topic_id"`                               // 话题ID
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName VideoTopic's table name
func (*VideoTopic) TableName() string {
	return TableNameVideoTopic
}
