// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameVideo = "videos"

// Video 视频表
type Video struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:视频ID" json:"id"`                      // 视频ID
	UserID        int64          `gorm:"column:user_id;not null;comment:作者ID" json:"user_id"`                                 // 作者ID
	Title         string         `gorm:"column:title;not null;comment:标题" json:"title"`                                       // 标题
	Description   string         `gorm:"column:description;comment:视频描述" json:"description"`                                  // 视频描述
	CoverURL      string         `gorm:"column:cover_url;not null;comment:封面URL" json:"cover_url"`                            // 封面URL
	VideoURL      string         `gorm:"column:video_url;not null;comment:视频URL" json:"video_url"`                            // 视频URL
	Duration      int32          `gorm:"column:duration;not null;comment:视频时长（秒）" json:"duration"`                            // 视频时长（秒）
	Width         int32          `gorm:"column:width;comment:视频宽度" json:"width"`                                              // 视频宽度
	Height        int32          `gorm:"column:height;comment:视频高度" json:"height"`                                            // 视频高度
	FileSize      int64          `gorm:"column:file_size;comment:文件大小（字节）" json:"file_size"`                                  // 文件大小（字节）
	MusicID       int64          `gorm:"column:music_id;comment:背景音乐ID" json:"music_id"`                                      // 背景音乐ID
	Province      string         `gorm:"column:province;comment:省份" json:"province"`                                          // 省份
	City          string         `gorm:"column:city;comment:城市" json:"city"`                                                  // 城市
	Location      string         `gorm:"column:location;comment:具体位置" json:"location"`                                        // 具体位置
	Latitude      float64        `gorm:"column:latitude;comment:纬度 (-90 to 90)" json:"latitude"`                              // 纬度 (-90 to 90)
	Longitude     float64        `gorm:"column:longitude;comment:经度 (-180 to 180)" json:"longitude"`                          // 经度 (-180 to 180)
	Status        int32          `gorm:"column:status;default:1;comment:状态：1-审核中，2-已发布，3-未通过，4-已下架" json:"status"`            // 状态：1-审核中，2-已发布，3-未通过，4-已下架
	ViewCount     int32          `gorm:"column:view_count;comment:播放次数" json:"view_count"`                                    // 播放次数
	LikeCount     int32          `gorm:"column:like_count;comment:点赞数" json:"like_count"`                                     // 点赞数
	CommentCount  int32          `gorm:"column:comment_count;comment:评论数" json:"comment_count"`                               // 评论数
	ShareCount    int32          `gorm:"column:share_count;comment:分享数" json:"share_count"`                                   // 分享数
	FavoriteCount int32          `gorm:"column:favorite_count;comment:收藏数" json:"favorite_count"`                             // 收藏数
	PublishedAt   time.Time      `gorm:"column:published_at;comment:发布时间" json:"published_at"`                                // 发布时间
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
