// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameViewHistory = "view_history"

// ViewHistory 播放历史表
type ViewHistory struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                        // ID
	UserID    int64     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                 // 用户ID
	VideoID   int64     `gorm:"column:video_id;not null;comment:视频ID" json:"video_id"`                               // 视频ID
	Duration  int32     `gorm:"column:duration;comment:观看时长（秒）" json:"duration"`                                     // 观看时长（秒）
	Progress  float64   `gorm:"column:progress;default:0.00;comment:观看进度（百分比）" json:"progress"`                      // 观看进度（百分比）
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName ViewHistory's table name
func (*ViewHistory) TableName() string {
	return TableNameViewHistory
}
